export const ADDED = "TODOS/ADDED";
export const TOGGLED = "TODOS/TOGGLED";
export const COLORSELECTED = "TODOS/COLORSELECTED";
export const DELETED = "TODOS/DELETED";
export const ALLCOMPLETED = "TODOS/ALLCOMPLETED";
export const CLEARCOMPLETED = "TODOS/CLEARCOMPLETED";
export const ALLDONE = "TODOS/ALLDONE";
