import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import doubleTick from "./images/double-tick.png";
import notes from "./images/notes.png";
import plus from "./images/plus.png";
import cancel from "./images/cancel.png";
import Footer from "./components/Footer";
import { Navbar } from "./components/Navbar";
import Header from "./components/Header";
import TodoList from "./components/TodoList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid place-items-center bg-blue-100 h-screen px-6 font-sans">
          <Navbar />

          <div className="w-full max-w-3xl shadow-lg rounded-lg p-6 bg-white">
            <Header />
            <hr className="mt-4" />

            <TodoList />

            <hr className="mt-4" />
            <Footer />
          </div>
        </div>
      </main>
    </>
  );
}
